/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "logout": [],
    "signup": [],
    "mahasiswa.dashboard": [],
    "mahasiswa.krs": [],
    "mahasiswa.jadwal": [],
    "mahasiswa.nilai": [],
    "dosen.dashboard": [],
    "dosen.persetujuan": [],
    "dosen.kelas": [],
    "dosen.jadwal": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
